export default {
	CHECK_LOGIN : 'CHECK_LOGIN',
	CHECK_LOGIN_SUCCESS : 'CHECK_LOGIN_SUCCESS',
	CHECK_LOGIN_FAIL : 'CHECK_LOGIN_FAIL',
	GET_RELEASE_REQUEST : 'GET_RELEASE_REQUEST',
	GET_RELEASE_SUCCESS : 'GET_RELEASE_SUCCESS',
	GET_RELEASE_FAIL : 'GET_RELEASE_FAIL',
}